# Generated by Django 3.2 on 2022-03-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_sender', models.CharField(max_length=70)),
                ('epoch_index', models.IntegerField()),
                ('input_index', models.IntegerField()),
                ('block_number', models.IntegerField()),
                ('time_stamp', models.IntegerField()),
                ('payload', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('BloodTipy', models.CharField(max_length=3)),
                ('Religion', models.CharField(max_length=70)),
            ],
        ),
    ]
