# Generated by Django 3.2 on 2022-02-07 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSQL', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='imputs',
            new_name='inputs',
        ),
    ]
