# Generated by Django 3.2 on 2022-02-24 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSQL', '0003_logs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inputs',
            new_name='Input',
        ),
        migrations.RenameModel(
            old_name='Logs',
            new_name='Log',
        ),
    ]
