# Generated by Django 3.2 on 2022-02-24 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSQL', '0004_auto_20220224_0247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Input',
        ),
    ]
