# Generated by Django 3.2 on 2022-02-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSQL', '0005_delete_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('BloodTipy', models.CharField(max_length=3)),
                ('Religion', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='payload',
            field=models.CharField(max_length=1000),
        ),
    ]
